In [1]:
from src.transformers.moebert.utils import DiffFeedForward
from transformers import AutoConfig
from transformers.models.bert.modeling_bert_moe import (
    MoEBertForSequenceClassification,
)

In [5]:
config = AutoConfig.from_pretrained("bert-base-uncased")
# model=DiffFeedForward(
#     config              =config,
#     intermediate_size   =config.intermediate_size,
#     shared_size         =1024,
#     dropout             =0.1,
#     fixmask_init        =False,
#     alpha_init          =5.0,
#     concrete_lower      =-1.5,
#     concrete_upper      =1.5,
#     structured          =True,
#     sparsity_pen        =1.25e-7,
# )
model=MoEBertForSequenceClassification.from_pretrained(config)

401 Client Error: Unauthorized for url: https://huggingface.co/BertConfig%20%7B%0A%20%20%22adapter_size%22:%20null,%0A%20%20%22adapter_type%22:%20null,%0A%20%20%22apply_adapter%22:%20false,%0A%20%20%22apply_lora%22:%20false,%0A%20%20%22architectures%22:%20%5B%0A%20%20%20%20%22BertForMaskedLM%22%0A%20%20%5D,%0A%20%20%22attention_probs_dropout_prob%22:%200.1,%0A%20%20%22gradient_checkpointing%22:%20false,%0A%20%20%22hidden_act%22:%20%22gelu%22,%0A%20%20%22hidden_dropout_prob%22:%200.1,%0A%20%20%22hidden_size%22:%20768,%0A%20%20%22initializer_range%22:%200.02,%0A%20%20%22intermediate_size%22:%203072,%0A%20%20%22layer_norm_eps%22:%201e-12,%0A%20%20%22lora_alpha%22:%20null,%0A%20%20%22lora_r%22:%20null,%0A%20%20%22max_position_embeddings%22:%20512,%0A%20%20%22model_type%22:%20%22bert%22,%0A%20%20%22num_attention_heads%22:%2012,%0A%20%20%22num_hidden_layers%22:%2012,%0A%20%20%22pad_token_id%22:%200,%0A%20%20%22position_embedding_type%22:%20%22absolute%22,%0A%20%20%22transformers_version%22:%

OSError: Can't load config for 'BertConfig {
  "adapter_size": null,
  "adapter_type": null,
  "apply_adapter": false,
  "apply_lora": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "lora_alpha": null,
  "lora_r": null,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.4.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}
'. Make sure that:

- 'BertConfig {
  "adapter_size": null,
  "adapter_type": null,
  "apply_adapter": false,
  "apply_lora": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "lora_alpha": null,
  "lora_r": null,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.4.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}
' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'BertConfig {
  "adapter_size": null,
  "adapter_type": null,
  "apply_adapter": false,
  "apply_lora": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "lora_alpha": null,
  "lora_r": null,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.4.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}
' is the correct path to a directory containing a config.json file



: 

In [3]:
model

NameError: name 'model' is not defined

In [7]:
a=model.fc1_shared.bias.shape
b=model.fc1_shared.weight.shape
print(a,b)

torch.Size([1024]) torch.Size([1024, 768])


In [9]:
idx = [0,1,2,3,4,5]
idx1 = idx[:3]
idx2 = idx[3:]
model.fc1_shared.bias[idx]

tensor([-0.0359, -0.0087,  0.0167,  0.0258,  0.0167,  0.0229],
       grad_fn=<IndexBackward>)

In [10]:
print(model.fc1_shared.bias[idx1])
print(model.fc1_shared.bias[idx2])

tensor([-0.0359, -0.0087,  0.0167], grad_fn=<IndexBackward>)
tensor([0.0258, 0.0167, 0.0229], grad_fn=<IndexBackward>)


In [13]:
b=model.fc1_shared.parametrizations.weight[0].alpha_group

In [14]:
c=a*b

In [15]:
c.shape

torch.Size([1024, 768])

In [ ]:
import pickle
import random
import torch

In [ ]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense2moe/rte/model/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [ ]:
a=ckpt["bert.encoder.layer.1.experts.experts.1.fc1.weight"]
print(a)

In [ ]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense/rte/model/checkpoint-3100/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [ ]:
ckpt["bert.encoder.layer.1.intermediate.dense.weight"]

In [ ]:
torch.where(ckpt["bert.encoder.layer.1.intermediate.dense.weight"] == a)

In [ ]:
a=torch.randint(low=0, high=32, size=(1,), device="cuda")

In [ ]:
a.detach().item()

In [ ]:
b=torch.nn.Parameter(a)

In [ ]:
num_layers  =
num_experts =4
vocab_size  =20000
with open("random_hash_ex{}_vocab{}.txt".format(num_experts, vocab_size), "r") as fin:
    hash_list = torch.
    fin.write()


In [ ]:
b

In [ ]:
ckpt.keys()

In [ ]:
with open("importance_files/importance_rte.pkl","rb") as fin:
    input = pickle.load(fin)
    print(input["idx"])

In [ ]:
a = torch.tensor(input)

In [ ]:
input[0]