In [1]:
from src.transformers.moebert.utils import DiffFeedForward
from transformers import AutoConfig

In [2]:
config = AutoConfig.from_pretrained("bert-base-uncased")
model=DiffFeedForward(
    config              =config,
    intermediate_size   =config.intermediate_size,
    shared_size         =1024,
    dropout             =0.1,
    fixmask_init        =False,
    alpha_init          =5.0,
    concrete_lower      =-1.5,
    concrete_upper      =1.5,
    structured          =True,
    sparsity_pen        =1.25e-7,
)

In [7]:
a=model.fc1_shared.bias.shape
b=model.fc1_shared.weight.shape
print(a,b)

torch.Size([1024]) torch.Size([1024, 768])


In [9]:
idx = [0,1,2,3,4,5]
idx1 = idx[:3]
idx2 = idx[3:]
model.fc1_shared.bias[idx]

tensor([-0.0359, -0.0087,  0.0167,  0.0258,  0.0167,  0.0229],
       grad_fn=<IndexBackward>)

In [10]:
print(model.fc1_shared.bias[idx1])
print(model.fc1_shared.bias[idx2])

tensor([-0.0359, -0.0087,  0.0167], grad_fn=<IndexBackward>)
tensor([0.0258, 0.0167, 0.0229], grad_fn=<IndexBackward>)


In [13]:
b=model.fc1_shared.parametrizations.weight[0].alpha_group

In [14]:
c=a*b

In [15]:
c.shape

torch.Size([1024, 768])

In [ ]:
import pickle
import random
import torch

In [ ]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense2moe/rte/model/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [ ]:
a=ckpt["bert.encoder.layer.1.experts.experts.1.fc1.weight"]
print(a)

In [ ]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense/rte/model/checkpoint-3100/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [ ]:
ckpt["bert.encoder.layer.1.intermediate.dense.weight"]

In [ ]:
torch.where(ckpt["bert.encoder.layer.1.intermediate.dense.weight"] == a)

In [ ]:
a=torch.randint(low=0, high=32, size=(1,), device="cuda")

In [ ]:
a.detach().item()

In [ ]:
b=torch.nn.Parameter(a)

In [ ]:
num_layers  =
num_experts =4
vocab_size  =20000
with open("random_hash_ex{}_vocab{}.txt".format(num_experts, vocab_size), "r") as fin:
    hash_list = torch.
    fin.write()


In [ ]:
b

In [ ]:
ckpt.keys()

In [ ]:
with open("importance_files/importance_rte.pkl","rb") as fin:
    input = pickle.load(fin)
    print(input["idx"])

In [ ]:
a = torch.tensor(input)

In [ ]:
input[0]