In [49]:
import pickle
import random
import torch

In [76]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense2moe/rte/model/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [77]:
a=ckpt["bert.encoder.layer.1.experts.experts.1.fc1.weight"]
print(a)

tensor([[ 0.0163,  0.0353, -0.0286,  ..., -0.0657, -0.0121, -0.0127],
        [ 0.0250, -0.0471, -0.0069,  ..., -0.0049,  0.0534, -0.0036],
        [ 0.0257, -0.0153,  0.0243,  ...,  0.0239, -0.0653, -0.0648],
        ...,
        [ 0.0294, -0.0633,  0.0392,  ..., -0.0290, -0.0735, -0.0086],
        [ 0.0034, -0.0028,  0.0405,  ...,  0.0104,  0.0326, -0.0052],
        [-0.0156, -0.0581,  0.0104,  ..., -0.0145, -0.0088,  0.0422]],
       device='cuda:0')


In [78]:
ckpt_name="/home/kimth/workspace/MoEBERT/ckpt/dense/rte/model/checkpoint-3100/pytorch_model.bin"
ckpt=torch.load(ckpt_name)

In [79]:
ckpt["bert.encoder.layer.1.intermediate.dense.weight"]

tensor([[ 0.0163,  0.0353, -0.0286,  ..., -0.0657, -0.0121, -0.0127],
        [ 0.0250, -0.0471, -0.0069,  ..., -0.0049,  0.0534, -0.0036],
        [ 0.0257, -0.0153,  0.0243,  ...,  0.0239, -0.0653, -0.0648],
        ...,
        [ 0.0294, -0.0633,  0.0392,  ..., -0.0290, -0.0735, -0.0086],
        [ 0.0034, -0.0028,  0.0405,  ...,  0.0104,  0.0326, -0.0052],
        [-0.0156, -0.0581,  0.0104,  ..., -0.0145, -0.0088,  0.0422]],
       device='cuda:0')

In [75]:
torch.where(ckpt["bert.encoder.layer.1.intermediate.dense.weight"] == a)

(tensor([ 425,  425,  425,  ..., 2117, 2117, 2117], device='cuda:0'),
 tensor([  0,   1,   2,  ..., 765, 766, 767], device='cuda:0'))

In [7]:
a=torch.randint(low=0, high=32, size=(1,), device="cuda")

In [8]:
a.detach().item()

12

In [10]:
b=torch.nn.Parameter(a)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [ ]:
num_layers  =
num_experts =4
vocab_size  =20000
with open("random_hash_ex{}_vocab{}.txt".format(num_experts, vocab_size), "r") as fin:
    hash_list = torch.
    fin.write()


In [ ]:
b

In [4]:
ckpt.keys()

dict_keys(['bert.embeddings.position_ids', 'bert.embeddings.word_embeddings.weight', 'bert.embeddings.position_embeddings.weight', 'bert.embeddings.token_type_embeddings.weight', 'bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.self.query.weight', 'bert.encoder.layer.0.attention.self.query.bias', 'bert.encoder.layer.0.attention.self.key.weight', 'bert.encoder.layer.0.attention.self.key.bias', 'bert.encoder.layer.0.attention.self.value.weight', 'bert.encoder.layer.0.attention.self.value.bias', 'bert.encoder.layer.0.attention.output.dense.weight', 'bert.encoder.layer.0.attention.output.dense.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.experts.experts.0.fc1.weight', 'bert.encoder.layer.0.experts.experts.0.fc1.bias', 'bert.encoder.layer.0.experts.experts.0.fc2.weight', 'bert.encoder.layer.0.experts.experts.0.fc2.bias', 'bert.encoder.layer.0

In [81]:
with open("importance_files/importance_rte.pkl","rb") as fin:
    input = pickle.load(fin)
    print(input["idx"])

[[1724, 2224, 219, 2643, 883, 368, 2772, 1548, 333, 135, 661, 1986, 2666, 2318, 1744, 1714, 46, 1825, 1244, 627, 1270, 2423, 657, 2002, 506, 2057, 1726, 1327, 371, 2030, 2670, 952, 22, 2773, 297, 2380, 2958, 1028, 2797, 197, 1870, 816, 464, 3035, 2201, 1133, 285, 1335, 283, 2089, 2587, 1345, 2090, 797, 1079, 2639, 1386, 1440, 2221, 1325, 1393, 1849, 2790, 489, 2920, 2118, 2514, 2568, 795, 807, 1501, 2945, 2156, 2421, 2062, 765, 2363, 1204, 1118, 1164, 1588, 1251, 826, 12, 2284, 75, 3040, 1441, 19, 307, 2890, 2077, 679, 955, 2242, 231, 958, 1300, 1444, 597, 61, 1202, 1892, 1288, 354, 1132, 68, 1873, 1143, 1864, 755, 2348, 485, 2996, 2625, 2384, 694, 2010, 1166, 537, 1103, 1686, 1975, 2236, 2721, 1021, 2738, 1126, 986, 1150, 1262, 2705, 2998, 2226, 1241, 932, 1460, 622, 2267, 229, 2646, 2868, 2949, 2820, 2731, 125, 650, 2255, 639, 552, 232, 500, 174, 327, 2713, 350, 444, 1844, 3065, 2472, 3071, 520, 2329, 172, 2693, 860, 2425, 1528, 1506, 2281, 2305, 24, 460, 769, 3053, 2431, 1205, 2080,

In [3]:
a = torch.tensor(input)

In [4]:
input[0]

[0.9480254054069519,
 2.0160863399505615,
 0.9048684239387512,
 2.301485538482666,
 1.7523330450057983,
 1.728222370147705,
 1.2347103357315063,
 1.340489387512207,
 3.168879508972168,
 4.1676154136657715,
 0.594732940196991,
 1.1659507751464844,
 10.622989654541016,
 0.8785038590431213,
 1.7278677225112915,
 2.2069525718688965,
 1.5173121690750122,
 0.7075143456459045,
 0.9015524983406067,
 3.3955185413360596,
 3.2566986083984375,
 2.495034694671631,
 15.904681205749512,
 2.107391119003296,
 4.758357048034668,
 1.7762246131896973,
 1.7728323936462402,
 2.2231171131134033,
 1.8211266994476318,
 1.9433751106262207,
 2.54109787940979,
 0.8689115643501282,
 1.2931348085403442,
 2.229417562484741,
 2.8644354343414307,
 3.3897905349731445,
 2.428595542907715,
 2.6072635650634766,
 0.5962826609611511,
 2.734708309173584,
 0.6591342687606812,
 2.4817826747894287,
 2.7385127544403076,
 2.431352376937866,
 3.0588912963867188,
 1.0759177207946777,
 18.929466247558594,
 1.4671375751495361,
 1.175